### ISSUE TITLE
No sound in keyboard example

### ISSUE THREAD

**Issue by niklassaers** [audiokit/Examples#14]
Hi,
when I launched the keyboard example of todays git clone of Examples, I got the following warnings:

0dBFS level = 32768.0
Csound version 6.04 (float samples) Apr 22 2015
libsndfile-1.0.26pre6
    2015-07-12 14:39:37.890 Keyboard[33615:7649277] 14:39:37.890 WARNING:   139: The default input device's sample rate was changed.
2015-07-12 14:39:38.415 Keyboard[33615:7649278] 14:39:38.415 WARNING:   256: Audio device's sample rate changed. You may need to restart the simulator.

When I played the keyboard, there was no sound. This was in Xcode 6.4 (6E35b) on an Yosemite iMac running the iPhone 5 simulator. Closing the simulator and starting it again did not change anything. Changing the simulator to others, such as the iPhone 6, did also not change anything.

Cheers

   Nik

**Comment by aure** [comment]
I am not able to reproduce this error.  Both the Objective-C and Swift Examples work on my machine.  Do any of the other examples make a sound?

**Comment by narner** [comment]
This repository is obsolete. AudioKit 3 contains playgrounds that replaced simple examples like the ones from this repo and contains better examples of real world apps.
